title: "Osprey Delight Demo"
baseURL: "https://example.com"
languageCode: "en-US"
theme: "osprey-delight"
tags: ["personal", "homepage", "portfolio"]
#canonifyURLS: true
#googleAnalytics: ""
disableKinds: ["taxonomy", "taxonomyTerm"]
enableEmoji: true
pygmentsUseClasses: true

module:
  imports:
  - path: github.com/kdevo/osprey-delight 

## Generic theme parameters:
Params:
  author: "kdevo"
  description: "Osprey Delight - Example Site"

  # logoBig appears at the top of the page. Use a path relative to the assets dir for auto-resizing. 
  logoBig: "osprey-delight.png"

  # logoSmall is the logo that will be shown in the left corner of the nav bar.
  #   Use a path relative to the assets dir for auto-resizing.
  logoSmall: "favicon.png"

  # tagline (followed by a cursor) is shown at the top, below the logo
  #tagline: "Welcome!"
  # mdTagline can be used instead to specify the tagline in Markdown for more customizability.
  #   Note that {cursor} is a placeholder and will be replaced by the actual cursor HTML when rendering.
  mdTagline: "# Welcome!\n ## This is Osprey Delight{cursor}"
  favicon: "favicon.png"

  opengraphImage: "/images/osprey-delight.png"

  # enforceSinglePage will enforce redirection to the baseURL for all sub-directories/-pages.
  #   Example: If you create about.md, Hugo will also create a '/about/index.html' which might not be what you want for a *single* page site. 
  #   If this switch is enabled, all these "orphan" files will contain only a redirect directive.
  enforceSinglePage: false

  # copyright flag generates a copyright notice in footer of your site.
  copyright: true

## Social links in footer:
  Social:
  - type: twitter # references the icon to use
    url: ""
  - type: linkedin 
    url: ""
  - type: github
    url: "https://github.com/kdevo/osprey-delight"
  - type: stackoverflow  
    url: ""
  - type: spotify
    url: https://open.spotify.com/artist/5NhBOdJh6T1tgtM5Au1Opl
  - type: bandcamp
    url: https://protonautmusic.bandcamp.com 


## Theme features:
  Feat:
    # ajaxBasin requires Basin setup for a free contact form (see instructions in README).
    ajaxBasin: "https://usebasin.com/f/{YOUR-12-CHAR-FORM-KEY-HERE}"

    # useStructuredData for your own https://schema.org/Person (SEO-friendly).
    #   This will be auto-generated dependent on the information you provide in this configuration.
    useStructuredData: false

    # structuredDataGitHubUser will tell the theme to use your USERNAME for querying the GitHub API to fetch more information about you for structured data.
    #   This will use information that is publically available about your GitHub user profile at https://api.github.com/users/{USERNAME}.
    #structuredDataGitHubUser = "USERNAME"

    # useTermynal enables Termynal (https://github.com/ines/termynal), a small JS library for showing a terminal "animation" from within your gallery item.
    #   The cool thing is that the library has been stripped-down to a minimum to only have the necessary functionality.
    useTermynal: true

    googleTagManager: ""
  
  # Image resizing can be configured here (see README for more info):
  Image:
    Logo:
      resize: "300x"

    Gallery:
      resize: "400x"

    # Background:
    #   resize: "1920x"
      

## Menu items are automatically added to navbar. Use content files for more advanced usage.
##   See: https://gohugo.io/content-management/menus/#add-content-to-menus
Menu:
  Main:
    - name: "About"
      # identifier controls the section type (and therewith the appearence).
      identifier: about 
      # url must be an anchor, for smooth scrolling to it when clicking on the menu item.
      url: "/#about"
      # weight controls the order of the menu items.
      weight: 1
    - name: "Work"
      identifier: gallery
      url: "/#work"
      weight: 2
    - name: "Blog"
      identifier: blog
      url: "/#blog"
      weight: 3
    - name: "Contact"
      identifier: contact
      url: "/#contact"
      weight: 4
    # - name: ""
    #   # pre makes it possible to use arbitrary HTML before the name, e.g. referencing icons here is possible:
    #   pre: '<svg class="icon"><use xlink:href="#icon-external"/></svg>&nbsp;'
    #   url: "https://pyotek.dev"
    #   weight: 5
